name: Publish
on:
  push:
    branches:
      - main
    tags:
      - v**

jobs:
  publish:
    name: Publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      generate-build-number: false
      conventional-commits-publish-conditions: false
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
